workflows:
  android-native-build:
    name: Native Android Build
    environment:
      java: 17
    scripts:
      - name: Extract source code
        script: |
          unzip -o voice_chat_app_source.zip -d .
      - name: Build Android APK
        script: |
          cd voice_chat_app_source
          ./gradlew assembleRelease
    artifacts:
      - voice_chat_app_source/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
