workflows:
  android-native-build:
    name: Native Android Build
    environment:
      java: 17
    scripts:
      - name: Extract source code
        script: |
          unzip -o voice_chat_app_source.zip -d .
          export PROJECT_DIR=$(find . -type f -name "gradlew" | head -n 1 | xargs dirname)
          echo "Project directory: $PROJECT_DIR"
      - name: Build Android APK
        script: |
          cd $PROJECT_DIR
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - $PROJECT_DIR/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
